### ISSUE TITLE
Video link is out of date for Terra Data Tables from the Broad.

### ISSUE THREAD

**Issue by aminards** [lynnlangit/gcp-for-bioinformatics#9]
The link to the Broad video on Terra Data tables in 5_Use_Terra.bio_Genomic_Datasets.md is depreciated.

**Comment by lynnlangit** [comment]
@aminards would it be possible for you to provide the most updated link (you can just PR and I'll merge it) - thanks!

**Comment by aminards** [comment]
@lynnlangit Sorry, I have no idea what the new link would be.  I just tried to go to it from your link and it is no longer there.

**Comment by lynnlangit** [comment]
Is it a link on this page (https://github.com/lynnlangit/gcp-for-bioinformatics/blob/master/1_Files_%26_Data/5_Use_Terra.bio_Genomic_Datasets.md)? which link?  they work for me

**Comment by aminards** [comment]
It is this link on this page https://github.com/lynnlangit/gcp-for-bioinformatics/blob/master/1_Files_%26_Data/5_Use_Terra.bio_Genomic_Datasets.md
In context of the page:

**More about the Terra Data Inputs Model - [link](https://gatkforums.broadinstitute.org/firecloud/discussion/9769/data-model)

Participant -> a person enrolled in a study
Sample -> a biological sample collected from a participant
Pair -> represents a pair of biological samples collected from a participant
Set -> group of Participants, Samples or Pairs**

**Comment by lynnlangit** [comment]
thanks so much updated (https://support.terra.bio/hc/en-us/articles/360033913771-Overview-Entity-types-and-the-standard-genomic-data-model)
